//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Rid { get; set; }
        public string empid { get; set; }
        public int pid { get; set; }
        public string cause { get; set; }
        public System.DateTime Fromdate { get; set; }
        public System.DateTime Todate { get; set; }
        public int noDays { get; set; }
        public string source { get; set; }
        public string Destination { get; set; }
        public string mode { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
